name: protbench
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2023.05.30
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=1.1.1t
  - pip=23.0.1
  - python=3.10.11
  - readline=8.2
  - setuptools=67.8.0
  - sqlite=3.41.2
  - tk=8.6.12
  - tzdata=2023c
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
      - absl-py==1.4.0
      - accelerate==0.20.3
      - appdirs==1.4.4
      - biopython==1.81
      - cached-property==1.5.2
      - certifi==2023.5.7
      - charset-normalizer==3.1.0
      - chex==0.1.7
      - click==8.1.3
      - cmake==3.26.4
      - dm-tree==0.1.8
      - docker-pycreds==0.4.0
      - etils==1.3.0
      - filelock==3.12.0
      - flax==0.6.10
      - fsspec==2023.5.0
      - gitdb==4.0.10
      - gitpython==3.1.31
      - huggingface-hub==0.15.1
      - idna==3.4
      - importlib-resources==5.12.0
      - jax==0.4.12
      - jaxlib==0.4.12
      - jinja2==3.1.2
      - joblib==1.2.0
      - lit==16.0.5.post0
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - mdurl==0.1.2
      - ml-dtypes==0.2.0
      - mpmath==1.3.0
      - msgpack==1.0.5
      - mypy-extensions==1.0.0
      - nest-asyncio==1.5.6
      - networkx==3.1
      - numpy==1.24.3
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - opt-einsum==3.3.0
      - optax==0.1.5
      - orbax-checkpoint==0.2.6
      - packaging==23.1
      - pathtools==0.1.2
      - pillow==9.5.0
      - protobuf==4.23.3
      - psutil==5.9.5
      - pygments==2.15.1
      - pyyaml==6.0
      - regex==2023.6.3
      - requests==2.31.0
      - rich==13.4.2
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - sentry-sdk==1.25.1
      - setproctitle==1.3.2
      - six==1.16.0
      - smmap==5.0.0
      - sympy==1.12
      - tensorstore==0.1.38
      - threadpoolctl==3.1.0
      - tokenizers==0.13.3
      - tomli==2.0.1
      - toolz==0.12.0
      - torch==2.0.1
      - torchaudio==2.0.2
      - torchvision==0.15.2
      - tqdm==4.65.0
      - transformers==4.29.2
      - triton==2.0.0
      - typing-extensions==4.6.3
      - urllib3==2.0.3
      - wandb==0.15.4