from protbench.src.tasks.residue_to_class import ResidueToClass
from protbench.src.tasks.residue_to_class import FastaResidueToClass
from protbench.src.tasks.residue_to_class import HuggingFaceResidueToClass