from protbench.models.heads import RegressionHead
from protbench.models.heads import BinaryClassificationHead
from protbench.models.heads import MultiClassClassificationHead
from protbench.models.heads import TokenClassificationHead
from protbench.models.heads import MultiLabelClassificationHead
from protbench.models.pooling import GlobalAvgPooling1D
from protbench.models.pooling import GlobalMaxPooling1D
from protbench.models.convbert import ConvBert
from protbench.models.downstream_model import DownstreamModel